### PR TITLE
Cleanup whitespace

### PR DESCRIPTION
**Pull request by dirk-zimoch**
This is purely cosmetic:
1. There was a mess with tab character usage. Indention with spaces and tabs was mixed inconsistently sometimes with obviously different assumptions on tab width, even in the same file. This results in irregular, hard to read indents. Please stop using tabs in source code.
2. Clean up of space at end of line.
3. Clean up of empty lines at end of file.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
defc676ccf762f099d9a8166496cadf218862e2e includes an update to the `.ci` submodule.  Can you edit this out?

**Comment by dirk-zimoch** [comment]
> [defc676](https://github.com/epics-base/pvAccessCPP/commit/defc676ccf762f099d9a8166496cadf218862e2e) includes an update to the `.ci` submodule. Can you edit this out?

How?

**Comment by mdavidsaver** [comment]
Since this was in the last commit, if you are using "git gui" (much recommended) it is simple.  Click "Amend Last Commit", unstage `.ci`, and click "commit".

The CLI process is to make the reverse change, then amend the last commit.

> cd .ci
> git checkout 7de5a7edc391d1b908828f2aa8118a5a6ce27021
> cd ..
> git add .ci
> git commit --amend

At this point, check to see that `.ci` isn't included in the commit.  Then force push.

**Comment by mdavidsaver** [comment]
Which I guess you've already figured out.

**Comment by dirk-zimoch** [comment]
I had problems to get the submodule back to its old state. Had to google it...

**Comment by mdavidsaver** [comment]
Such a burden ;)

**Pull request merged**
