### PR TITLE
fix all problems raised in issue #71

### PR DESCRIPTION
**Pull request by mrkraimer**
I still want to do more testing but want this does seem to fix all problems in issue #71

### CODE REVIEW

**Comment by mrkraimer** [comment]
Not that the only change I made in last push was to merge from epics-base.
.
Andrew and Sinisa,
I am ready for you to merge this pull request

**Comment by anjohnson** [comment]
Hi Marty, I just talked to Siniša about PR; he will be working on it (building and testing it) but may not have time to finish until Monday, so be assured it is still in line to be merged before the -rc1 release.

**Comment by sveseli** [comment]
The initial testing indicates that issues raised in #71 (timestamp, introspection data) have been fixed with commit 46b1986:
```
bluegill2> caget -a string01
string01                       2017-11-27 10:25:36.459640 10.1  
bluegill2> git status
# HEAD detached at 46b1986
nothing to commit, working directory clean
bluegill2> which pvget
/local/sveseli/Work/EPICS4/support-3.15/epics/modules/epics4-cpp-mk/pvAccessCPP-mk/bin/linux-x86_64/pvget
bluegill2> pvget -p ca -r "" string01
string01
epics:nt/NTScalar:1.0 
    string value 10.1
    alarm_t alarm NO_ALARM NO_STATUS NO_ALARM
    time_t timeStamp 2017-11-27T10:25:36.460 0


bluegill2> which pvinfo
/local/sveseli/Work/EPICS4/support-3.15/epics/modules/epics4-cpp-mk/pvAccessCPP-mk/bin/linux-x86_64/pvinfo
bluegill2> pvinfo -p ca string01
CHANNEL  : string01
STATE    : CONNECTED
ADDRESS  : bluegill2.aps.anl.gov:5064
epics:nt/NTScalar:1.0
    string value
    alarm_t alarm
        int severity
        int status
        string message
    time_t timeStamp
        long secondsPastEpoch
        int nanoseconds
        int userTag
```
However, if I try retrieving unknown channel pvget fails silently without any indication of the underlying problem:
```
bluegill2> caget non_existent_channel
Channel connect timed out: 'non_existent_channel' not found.
bluegill2> pvget -p ca non_existent_channel
bluegill2> echo $?
1
```

The problem does not seem to be related to ca provider:
```
bluegill2> pvget  non_existent_channel
bluegill2> echo $?
1
bluegill2> 
```
If I use old (4.6.0) version of pvget, I see proper error message:
```
bluegill2> pvget non_existent_channel
[non_existent_channel] connection timeout
```

**Comment by gregoryraymondwhite** [comment]
Hi Ralph, this reminds me of your clarification about adding introspection query for ca - not pva. Thanks. It didn’t occur to me that it was about ca, since all our pva stuff presently is RPC, and the introspection stuff isn’t supported by the servers, so pvinfo never gives us introspection data. So I forgot that of course, the usual case is for pvinfo to give you that, and so I didn’t make the obvious jump that what was being referred to must be ca. 

Cheers
Greg

**Comment by anjohnson** [comment]
I just read Siniša's response (he showed it to me this morning before posting but I didn't completely understand what he was saying, probably caused by a coffee deficiency on my part). Marty's changes in this PR do not cause the problem of no response from pvget, so I am now in favor of merging them and creating another issue about the absence of any output from pvget when the PV can't be found.

Using a version of pvget built from a git checkout dated July 19th I get a different error message than Siniša, but only from the CA provider:
```
tux% bin/linux-x86_64/pvget -p ca no-such-ca-pv
[no-such-ca-pv] failed to get: Status [type=ERROR, message=Virtual circuit disconnect]
tux% bin/linux-x86_64/pvget no-such-pva-pv
tux%
```
The CA response did come back very quickly there, and specifying `-w 3` made no difference to the wait time.

**Comment by mdavidsaver** [comment]
> If I use old (4.6.0) version of pvget, I see proper error message:

This has to do with changes I made to pvget over the summer.  Among other things, gets aren't sequential anymore.  For some reason I can't remember it only printed "Timeout" when run with "-d".  I've changed this now to always print.  This still doesn't give the nice per-PV error, but seems better for now.

**Pull request merged**
