### PR TITLE
flow initialization: Created <master> trunk: master.

### PR DESCRIPTION
**Pull request by mrkraimer**
Matej,

Can you merge mrkraimer/pvAccessCPP into epics-base/pvAccessCPP

Thanks,

Marty

### CODE REVIEW

**Comment by ralphlange** [comment]
Marty,

The commit you are proposing to merge (creation of branch called master) was an artifact created as a side effect of Matej using the hg flow plugin.

I do not think we should merge this branch, because:
* we are not on Mercurial anymore
* we are not using the flow development model anymore
* the main development branch is now called "master".

**Comment by mrkraimer** [comment]
This was meant to be a request for Matej to merge from
https://github.com/mrkraimer/pvAccessCPP

I do not know what I did wrong that made it look like a request to merge from mercurial.

Let me restate the request:

Matej,

Please merge"
https://github.com/mrkraimer/pvAccessCPP

into

https://github.com/epics-base/pvAccessCPP

Marty

**Comment by ralphlange** [comment]
Your development seems to be on a branch called "default".
The main repository's development branch is called "master".

Your pull request is for the "master" branch on your personal repo, which is most probably not what you intend.

**Comment by mrkraimer** [comment]
This is because I stated work on 
https://github.com/mrkraimer/pvAccessCPP

before master was made the main branch.
Thus I do want Matej to merge from default branch of

https://github.com/mrkraimer/pvAccessCPP

to the master branch of

https://github.com/epics-base/pvAccessCPP

Marty

**Comment by ralphlange** [comment]
I understand.

Your pull request, however, asks for your master branch to be merged into the master branch of the central repo, which is wrong.

Please create a new pull request that is pointing to the correct branch on your side.

**Comment by mrkraimer** [comment]
The last message I sent DID say to merge from the default branch.
So request is the same.

Matej please merge from default branch of
https://github.com/mrkraimer/pvAccessCPP
to the master branch of
https://github.com/epics-base/pvAccessCPP

Marty

**Comment by ralphlange** [comment]
Your message was clear.

Your pull request, however, asks for your master branch to be merged into the master branch of the central repo, which is wrong.
The concerned branches are part of the pull request itself. Look at the very top, just under the title of the pull request, to see which branches are requested to be pulled.

**Comment by ralphlange** [comment]
Thanks for not insisting to merge the wrong branch. ;-)

**Pull request closed without merging**
