### PR TITLE
merge of major gateway support changes to master branch

### PR DESCRIPTION
**Pull request by msekoranja**

### CODE REVIEW

**Comment by mrkraimer** [comment]
On 03/02/2016 07:34 AM, Matej Sekoranja wrote:
>
> Merged #27 <https://github.com/epics-base/pvAccessCPP/pull/27>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/pvAccessCPP/pull/27#event-574592106>.
>

It still does not work with base 3.15.3

Marty

**Comment by msekoranja** [comment]
@mrkraimer What does not work? Are you taking about security issue w/ multiple providers? If so, you need to take pvaSrv w/ the pull request I've created today:
https://github.com/epics-base/pvaSrv/pull/31

**Comment by mrkraimer** [comment]
On 03/02/2016 08:34 AM, Matej Sekoranja wrote:
>
> @mrkraimer <https://github.com/mrkraimer> What does not work? Are you 
> taking about security issue w/ multiple providers? If so, you need to 
> take pvaSrv w/ the pull request I've created today:
> epics-base/pvaSrv#31 <https://github.com/epics-base/pvaSrv/pull/31>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/pvAccessCPP/pull/27#issuecomment-191239700>.
>

I do not see that this was merged into master.

**Comment by mrkraimer** [comment]
On 03/02/2016 08:34 AM, Matej Sekoranja wrote:
>
> @mrkraimer <https://github.com/mrkraimer> What does not work? Are you 
> taking about security issue w/ multiple providers? If so, you need to 
> take pvaSrv w/ the pull request I've created today:
> epics-base/pvaSrv#31 <https://github.com/epics-base/pvaSrv/pull/31>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/pvAccessCPP/pull/27#issuecomment-191239700>.
>
Look at
https://github.com/epics-base/pvaSrv/pull/31

It shows that change as not merged.

Marty

**Comment by mdavidsaver** [comment]
> I do not see that this was merged into master.

If you're referring to epics-base/pvaSrv#31 then no.  The pull request is open and awaiting comments/test results...

**Comment by mrkraimer** [comment]
On 03/02/2016 11:07 AM, mdavidsaver wrote:
>
>     I do not see that this was merged into master.
>
> If you're referring to epics-base/pvaSrv#31 
> <https://github.com/epics-base/pvaSrv/pull/31> then no. The pull 
> request is open and awaiting comments/test results...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/pvAccessCPP/pull/27#issuecomment-191304820>.
>
I built with base 3.15.3 and with Matej's pvaSrv.

exampleCPP/test now works!!!

**Pull request merged**
