### PR TITLE
pipeline support

### PR DESCRIPTION
**Pull request by msekoranja**

### CODE REVIEW

**Comment by dhickin** [comment]
<p>Matej</p>

<p>Could you add a some more information about what the pipeline service is or point to some document describing it more fully?</p>

<p>Without a better understanding of the service, it's not obvious to me whether this belongs in pvAccess or someone else.</p>

<p>The service is a ChannelProvider. Generally I would expect new channel providers to go in separate middleware modules (like with pvaSrv and pvDatabaseCPP). RPCServer was an exception because it is so lightweight and generic. It made sense to put caProvider there too as the alternative provider to pva using ca.</p>

<p>Currently, with a few exceptions, pvDataCPP implements the pvData types, pvAccessCPP implements the pvAccess spec, normativeTypeCPP implements the normative types spec. Middleware is built on top of the two core modules. The delineation is reasonably clear.  I wouldn't want to see pvAccess get bloated with non-core stuff.</p>

<p>Not saying it shouldn't go in, but I'd like more info.</p>

<p>Also we're still in the process of getting the release out and I'm very busy. I'm guessing a few other people are too.</p>

<p>Can we put a <b>HOLD</b> on this until the release is out, we have a bit more information, we've had time to look at the request and we are able to discuss it?</p>

**Comment by msekoranja** [comment]
Pull request rejected. Implemented a solution that does not required pvData change.
I moved reportRemoteQueueStatus method from epics::pvData::Monitor to separate interface epics::pvAccess::PipelineMonitor.

**Comment by gregoryraymondwhite** [comment]
Hi Bruno

> Can we put a HOLD on this until the release is out,

Yes, in fact definitely.

Also, anything added in pvAccess library functionality, will/must/I hope (Matej tell me you’re listening) be added to the specification.

Cheers
Greg

**Comment by msekoranja** [comment]
> On 15 Oct 2015, at 23:12, Greg White <notifications@github.com> wrote:
> 
> Hi Bruno 
> 
> > Can we put a HOLD on this until the release is out, 
> 
> Yes, in fact definitely. 

This is why we have release branches. This way the development on the master branch can independently continue (and does not affect the release).

Pipelining is in use at NSLS II. They asked me to merge code before the release. I’ve delayed the merge until we have release/4.1 branch created.

> Also, anything added in pvAccess library functionality, will/must/I hope (Matej tell me you’re listening) be added to the specification. 

I will update the specification in a short term (hopefully next week). Maybe I will even start today.

Cheers,
Matej

>

**Pull request closed without merging**
